/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Actividad_11;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import javafx.scene.chart.Chart;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author liooficial
 */
public class serve extends javax.swing.JFrame {

    /**
     * Creates new form can
     */
    public serve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("establecer connexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            boolean s=false;
            JOptionPane.showMessageDialog(null,"CONEXIN EXITOSA");
            do{
            ServerSocket serverSocket = new ServerSocket(1234);
            Socket clientSocket = serverSocket.accept();
            PrintWriter out = new PrintWriter(clientSocket.getOutputStream(), true);
            BufferedReader in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            String inputLine = in.readLine();
            String outputLine;
            if(inputLine.equals("SALIR")||inputLine.equals("salir")){
                s=true;
                outputLine ="adios";
            }else{
            System.out.println("Servidor");
            System.out.println("Recibiendo: " + inputLine);
             outputLine = operacion(inputLine);
            System.out.println("Enviando: " + outputLine);
            }
            out.println(outputLine);
            out.close();
            in.close();
            clientSocket.close();
            serverSocket.close();
            }while(s!=true);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public String operacion(String  expresión){
        String[] split = expresión.split(",", -1);
        String s=""; 
        int n1=0,n2=0,r=0;
        for (int i = 0; i < split.length; i++) {
            if (i == 0) {
                s=split[i];
            } 
            if (i == 1 ) {
                n1=Integer.valueOf(split[i]);
            }
            if (i == 2) {
                n2=Integer.valueOf(split[i]);
            }
        }
        String resultado="";
        switch (s) {
            case "+":
                r=n1+n2;
                break;
            case "-":
                r=n1-n2;
                break;
            case "*":
                r=n1*n2;
                break;
            case "/":
                r = n1 / n2;
                break;
        }
        resultado=String.valueOf(r);
        return resultado;
    }
    /**
     * String[] split = cadena.split(",", -1);
            System.out.println("Recibiendo: " + split[1]+" "+split[2]);
            
            for (int i=0; i>=3; i++){
              if(i==1){
                  myString=split[i];
                  System.out.println(""+myString);
              }
              if(i==2){
                 n1=Integer.parseInt(split[i]);
                 System.out.println(""+n1);
              }
              if(i==3){
                 n2=Integer.parseInt(split[i]);
                 System.out.println(""+n2);
              }
            }
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
